#!/bin/sh

# Visual
bspc config border_width       		10
bspc config window_gap         		30
bspc config split_ratio         	0.52

bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true
bspc config auto_alternate 		true
bspc config auto_cancel 		true

bspc config normal_border_color 	"#4A3637"
bspc config focused_border_color 	"#775759"

bspc config active_border_color 	"#FFFFFF"
bspc config presel_border_color 	"#FFFFFF"
bspc config urgent_border_color 	"#FFFFFF"
bspc config focused_locked_border_color "#FFFFFF"

bspc config normal_frame_opacity 	0.0
bspc config focused_frame_opacity 	0.1

# Setup
i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {1,2,3,4,5,6,7,8,9,10}
    let i++
done
NMON=$i
unset i

~/Scripts/panel &
