#!/bin/sh

# Visual
bspc config border_width                4
bspc config window_gap                  100
bspc config split_ratio                 0.50

bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config auto_alternate              true
bspc config auto_cancel                 true

bspc config normal_border_color         "#4A3637"
bspc config focused_border_color        "#775759"

bspc config active_border_color         "#EEEEEE"
bspc config presel_border_color         "#EEEEEE"
bspc config urgent_border_color         "#EEEEEE"
bspc config focused_locked_border_color "#EEEEEE"

bspc config normal_frame_opacity        0.00
bspc config focused_frame_opacity       1.00

# Setup
COUNT="$(xrandr -d :0 -q | grep ' connected' | wc -l)"

if [ $COUNT -eq 2 ]
then
  bspc monitor eDP1 -d I II III IV V
  bspc monitor HDMI2 -d VI VII VIII IX X
else
  bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

bspc rule -a battery.py floating=on focus=on

# Include panel
~/Scripts/panel &
